Giyong8504/teamProject_Book

src/main/resources/templates/admin/outlines/_side.html
회의 내용 
메뉴명 , 순서 작성.
회의 내용 대로 담당 파트의 메뉴명 및 순서 작성 완료되었습니다.
=> 메뉴 및 순서 구성완료

src/main/resources/templates/admin/outlines/_side.html
branch 제대로 구성되는지 확인했습니다!
관리자 메인 사이드 항목 중 고객 문의/리뷰 부분 아이콘을 수정했습니다!
=> branch 구성 확인

src/main/java/org/teamproject/entities/Books.java
=> Books 엔터티 추가

src/main/java/org/teamproject/controllers/member/MemberController.java
=> 데이터 json방식  변환준비

src/main/java/org/teamproject/controllers/admin/ClaimController.java, src/main/resources/templates/admin/claim.html, src/main/resources/templates/admin/outlines/_side.html
_side.html claim 아이콘 변경하고,
ClaimController, claim.html 작성하여 취소/교환/반품 클릭 시 claim.html 페이지 이동 연결하였습니다.
=> 0921 _side.html claim 아이콘 변경,

src/main/java/org/teamproject/commons/InquiryReview/InquiryBoardService.java, src/main/java/org/teamproject/controllers/InquiryReview/InquiryController.java, src/main/java/org/teamproject/controllers/admin/ReviewController.java, src/main/java/org/teamproject/entities/InquiryBoard.java, src/main/java/org/teamproject/repositories/InquiryRepository.java, src/main/resources/templates/admin/review.html, src/main/resources/templates/front/InquiryReview/InquiryWrite.html
localhost:3000/admin/review 경로 이동에 필요한 것들을 설정했습니다.
=> 관리자 페이지 ReviewController, review.html 초기 구성

src/main/resources/static/admin/css/style.css, src/main/resources/static/admin/js/common.js, src/main/resources/templates/admin/claim.html
claim.html, admin/css/style.css, admin/js/common.js 작성 
주문/취소/교환페이지(claim.html)에서 주문목록 검색할 수 있는 검색창과 , 기간에 따라 주문목록을 확인할 수 있는 버튼 작성했습니다.
=> 0921 claim.html, admin/css/style.css, admin/js/common.js 작성

src/main/java/org/teamproject/controllers/member/BookForm.java, src/main/java/org/teamproject/controllers/member/MemberController.java, src/main/resources/messages/commons.properties, src/main/resources/messages/validations.properties, src/main/resources/templates/front/member/book.html
=> insert Book

src/main/java/org/teamproject/controllers/InquiryReview/InquiryController.java, src/main/resources/templates/front/InquiryReview/InquiryWrite.html
문의글 작성을 게시글 형식으로 작업하던 도중, DB에 올라가지 않는 오류를 수정했습니다
=> 문의글 작성(게시글 형식) 화면 작업중

src/main/java/org/teamproject/controllers/member/BookController.java, src/main/java/org/teamproject/controllers/member/BookForm.java, src/main/java/org/teamproject/entities/Books.java, src/main/java/org/teamproject/entities/Cart.java, src/main/java/org/teamproject/entities/CartItem.java, src/main/java/org/teamproject/models/book/BooksManageService.java, src/main/java/org/teamproject/repositories/BooksRepository.java, src/main/java/org/teamproject/repositories/CartItemRepository.java, src/main/java/org/teamproject/repositories/CartRepository.java
책 상품과 장바구니를 위한 엔티티, 레포지토리 구현
책 등록, 수정, 삭제를 위한 Service, Controller 구현중
이후 html 메인 페이지 구현 예정
=> 책 등록, 수정, 삭제를 위한 Service, Controller 구현중

src/main/java/org/teamproject/configs/AuditorAwareImpl.java, src/main/java/org/teamproject/entities/BaseMemberEntity.java, src/main/java/org/teamproject/models/member/files/FileDeleteService.java, src/main/java/org/teamproject/models/member/files/FileUploadService.java
@CreateBy, @ LastModifiedBy 자료형을 Long 에서 String으로 변경.
AuditorAwareImpl 클래스도 String으로 변경.
파일 삭제 권한 체크 빈값 일 경우 추가.
파일 업로드 작업중
- 파일 정보를 먼저 저장 후 처리.
=> 자료형 변경, 파일 업로드 작업중

src/main/java/org/teamproject/models/files/FileDeleteService.java, src/main/java/org/teamproject/models/files/FileDownloadService.java, src/main/java/org/teamproject/models/files/FileInfoService.java, src/main/java/org/teamproject/models/files/FileNotFoundException.java, src/main/java/org/teamproject/models/files/FileUploadService.java, src/main/java/org/teamproject/models/member/files/FileDownloadService.java
=> 패키지 경로변경,파일경로 체크 후 없을 경우 생성

src/main/resources/static/front/css/style.css, src/main/resources/templates/front/outlines/header.html
=> 메인페이지 헤더 작업 중

src/main/java/org/teamproject/controllers/member/EventController.java, src/main/java/org/teamproject/controllers/statusmember/StatsController.java, src/main/resources/static/admin/css/style.css, src/main/resources/templates/admin/stats.html, src/main/resources/templates/front/member/event.html
이벤트  화면 준비 및 경로 설정 
(바로 master pull  merge 후 다시 한번 더 커밋 하겠습니다)
=> 이벤트 화면 준비 및 경로 설정

src/main/java/org/teamproject/configs/interceptors/CommonInterceptor.java, src/main/java/org/teamproject/controllers/admin/BoardController.java, src/main/java/org/teamproject/entities/Board.java, src/main/java/org/teamproject/models/board/config/BoardConfigInfoService.java, src/main/java/org/teamproject/models/board/config/BoardConfigNotExistException.java, src/main/java/org/teamproject/models/board/config/BoardNotAllowAccessException.java, src/main/resources/application-dev.properties, src/main/resources/messages/validations.properties, src/main/resources/templates/admin/board/config.html
게시판 등록 작업을 완료했습니다! 이제 수정 작업을 진행하고 있습니다.
=> 게시판 등록/수정 오류 수정

src/main/java/org/teamproject/commons/constants/BookStatus.java, src/main/java/org/teamproject/controllers/TestController.java, src/main/java/org/teamproject/controllers/admin/ProductController.java, src/main/java/org/teamproject/controllers/admin/ProductForm.java, src/main/java/org/teamproject/entities/Books.java, src/main/java/org/teamproject/models/files/FileUploadService.java, src/main/java/org/teamproject/restcontrollers/CommonRestController.java, src/main/java/org/teamproject/restcontrollers/files/FileController.java, src/main/resources/static/common/js/fileManager.js, src/main/resources/templates/admin/outlines/_side.html, src/main/resources/templates/admin/product/_form.html, src/main/resources/templates/admin/product/add.html, src/main/resources/templates/admin/product/edit.html, src/main/resources/templates/test.html
=> 파일 업로드 완료. 상품등록, 수정 작업중.

src/main/java/org/teamproject/commons/Menu.java, src/main/java/org/teamproject/controllers/admin/ProductController.java, src/main/resources/templates/admin/product/add.html, src/main/resources/templates/admin/product/edit.html
파일 업로드 페이지 연결
- 이미지 추가와 연동(작업중)
상품 관리에 상품 수정 추가(확인 후 주문 목록에서 접근하도록 변경 예정)
mode 사용
=> 상품 등록 페이지 연결, 상품 수정 추가(확인 후 주문목록 접근으로 변경예정), mode 사용

src/main/java/org/teamproject/controllers/admin/ProductForm.java, src/main/resources/templates/admin/product/_form.html, src/main/resources/templates/admin/product/add.html
상품 등록 페이지 구성 중
- 기본적인 등록 작성 부분 구성.
- 배송 설정(진행중)
- 반품 설정(진행중)
=> 상품 등록 페이지 구성 중

src/main/java/org/teamproject/commons/Menu.java, src/main/java/org/teamproject/controllers/admin/OrderController.java, src/main/java/org/teamproject/entities/product/Order.java, src/main/java/org/teamproject/repositories/OrderRepository.java, src/main/resources/templates/admin/order/index.html
주문관리 menu, 엔터티, 페이지연결(선작업)
- 상품등록 페이지에서 등록된 필요한 정보 내용 확인을 위해 선작업 진행함.
- 주문관리 하위 메뉴 추가
- 엔터티 작성
- 컨트롤러
- 페이지 연결
=> 주문관리 menu, 엔터티, 페이지연결(선작업)

README.md
=> README 업데이트 협업툴 링크

src/main/java/org/teamproject/entities/Board.java, src/main/java/org/teamproject/models/board/config/BoardConfigInfoService.java, src/main/resources/static/front/js/board/form.js, src/main/resources/templates/board/skins/default/_form.html
게시글 작성을 ckeditor를 통해서도 할 수 있게 구현하는 중입니다
=> 게시판 프런트 구성 중

src/main/java/org/teamproject/controllers/admin/ProductForm.java, src/main/java/org/teamproject/entities/Books.java, src/main/resources/static/admin/js/book/form.js, src/main/resources/static/common/js/common.js, src/main/resources/static/common/js/fileManager.js, src/main/resources/templates/admin/product/_form.html, src/main/resources/templates/admin/product/add.html
- fileManager 수정
- 파일 업로드수정
- Books 엔터티 수정
=> fileManager 수정, 파일업로드수정, Books엔터티 수정

src/main/java/org/teamproject/entities/Books.java, src/main/resources/templates/admin/product/_form.html
Books엔터티 category 수정
_form에 name값 수정
=> Books엔터티 category 수정, _form에 name값 수정

src/main/java/org/teamproject/commons/Menu.java
=> Menu 상품수정 삭제(상품목록에서 연결)

src/main/java/org/teamproject/commons/constants/BookStatus.java, src/main/java/org/teamproject/commons/constants/OrdersStatus.java, src/main/java/org/teamproject/models/orders/OrdersInfoService.java, src/main/java/org/teamproject/repositories/BooksRepository.java
BooksRepository
- Querydsl 추가
BookStatus
- 상태추가
OrdersStatus
- 상태추가
=> book,orders status 추가

src/main/java/org/teamproject/controllers/admin/ProductController.java, src/main/java/org/teamproject/controllers/admin/ProductForm.java, src/main/java/org/teamproject/controllers/member/BookController.java, src/main/java/org/teamproject/entities/Books.java, src/main/java/org/teamproject/models/categories/CategoryInfoService.java, src/main/java/org/teamproject/models/categories/CategoryRegistService.java, src/main/java/org/teamproject/models/categories/CategoryUpdateService.java, src/main/java/org/teamproject/models/products/BookNotFoundException.java, src/main/java/org/teamproject/models/products/OutOfStockException.java, src/main/java/org/teamproject/models/products/ProductInfoService.java
패키지명, 위치 변경
- product -> categories
- products 패키지 생성
Books 엔티티 내용 추가
ProductForm 내용 추가
productInfoService작성중
=> 패키지명 위치 변경, Books 엔티티 ProductForm 내용 추가

src/main/java/org/teamproject/controllers/admin/ProductForm.java, src/main/java/org/teamproject/models/categories/CategoryInfoService.java, src/main/java/org/teamproject/models/product/BookNotFoundException.java, src/main/java/org/teamproject/models/product/OutOfStockException.java, src/main/java/org/teamproject/models/product/ProductInfoService.java, src/main/java/org/teamproject/models/product/ProductSearch.java
=> productSearch 생성

src/main/java/org/teamproject/controllers/admin/ProductForm.java, src/main/java/org/teamproject/models/product/ProductDeleteService.java, src/main/java/org/teamproject/models/product/ProductSaveService.java
=> 상품 삭제, 저장 기능

src/main/resources/messages/commons.properties, src/main/resources/templates/front/member/login.html
=> 아이디 비밀번호 찾기 버튼 추가

src/main/java/org/teamproject/controllers/admin/ProductController.java, src/main/java/org/teamproject/models/product/ProductSearch.java, src/main/resources/templates/admin/product/index.html
=> 상품 목록 페이지 구성 중

src/main/java/org/teamproject/commons/Menu.java
=> 게시판 menu 부분 수정

src/main/java/org/teamproject/models/categories/CategoryInfoService.java, src/main/java/org/teamproject/models/product/ProductSaveService.java
=> 카테고리 조회추가, 상품저장서비스 수정

src/main/java/org/teamproject/controllers/admin/ProductController.java, src/main/resources/templates/admin/product/index.html
=> 상품 조회/수정 구성

src/main/java/org/teamproject/controllers/admin/OrdersController.java, src/main/java/org/teamproject/controllers/member/cart/CartController.java, src/main/java/org/teamproject/controllers/member/cart/OrderController.java, src/main/java/org/teamproject/controllers/orders/OrdersSearch.java, src/main/java/org/teamproject/models/orders/CartInfoDeleteService.java, src/main/java/org/teamproject/models/orders/CartInfoSaveService.java, src/main/java/org/teamproject/models/orders/CartInfoService.java, src/main/java/org/teamproject/models/orders/CartItemNotFoundException.java, src/main/java/org/teamproject/models/orders/OrderSaveService.java
- 클래스 위치 변경
- cart 패키지에 클래스를 orders로 옮김.
- OrderSearch 생성
- OrderController작업중
=> 클래스 위치 변경, OrderSearch생성, OrderController 작업중

src/main/java/org/teamproject/controllers/admin/OrdersController.java
=> admin 페이지 주문목록 Controller 작업중

src/main/java/org/teamproject/commons/ScriptExceptionProcess.java, src/main/java/org/teamproject/controllers/admin/ProductController.java, src/main/java/org/teamproject/controllers/admin/dtos/ProductForm.java, src/main/java/org/teamproject/controllers/admin/products/ProductController.java, src/main/java/org/teamproject/controllers/member/BookController.java, src/main/java/org/teamproject/entities/Books.java, src/main/java/org/teamproject/models/categories/CategoryInfoService.java, src/main/java/org/teamproject/models/orders/CartInfoService.java, src/main/java/org/teamproject/models/orders/OrdersInfoService.java, src/main/java/org/teamproject/models/product/BookNotFoundException.java, src/main/java/org/teamproject/models/product/ProductDeleteService.java, src/main/java/org/teamproject/models/product/ProductInfoService.java, src/main/java/org/teamproject/models/product/ProductSaveService.java, src/main/java/org/teamproject/restcontrollers/files/FileController.java, src/main/resources/messages/commons.properties, src/main/resources/static/admin/js/common.js, src/main/resources/static/admin/js/product/form.js, src/main/resources/static/common/js/fileManager.js, src/main/resources/templates/admin/product/_form.html, src/main/resources/templates/admin/product/add.html, src/main/resources/templates/admin/product/edit.html
상품등록, 수정구현 완료 
- ProductForm, ProductController 수정
- Books 엔터티 isbn 추가
- CategoryInfoService의 Book 조회 부분 삭제
- BookNotFound 수정
- js추가
- _form수정
- productInfoService 수정
- productSaveService 수정
=> 상품등록, 수정구현 완료 (BookNotFound수정,js추가,_form수정)

src/main/java/org/teamproject/configs/MvcConfig.java, src/main/java/org/teamproject/controllers/admin/BoardController.java, src/main/java/org/teamproject/controllers/admin/BoardSearch.java, src/main/java/org/teamproject/controllers/boards/BoardController.java, src/main/java/org/teamproject/controllers/member/JoinForm.java, src/main/java/org/teamproject/entities/Board.java, src/main/java/org/teamproject/entities/BoardView.java, src/main/java/org/teamproject/entities/BoardViewId.java, src/main/java/org/teamproject/entities/Member.java, src/main/java/org/teamproject/models/board/config/BoardConfigInfoService.java, src/main/java/org/teamproject/models/board/config/BoardConfigListService.java, src/main/java/org/teamproject/models/board/config/BoardConfigSaveService.java, src/main/java/org/teamproject/models/board/config/UpdateHitService.java, src/main/java/org/teamproject/repositories/BoardViewRepository.java, src/main/resources/messages/validations.properties, src/main/resources/static/admin/css/style.css, src/main/resources/static/front/js/board/form.js, src/main/resources/templates/admin/board/config.html, src/main/resources/templates/admin/board/posts.html, src/main/resources/templates/admin/commons/_submenu.html, src/main/resources/templates/board/skins/default/_board_title.html, src/main/resources/templates/board/skins/default/_form.html, src/main/resources/templates/board/skins/default/list.html, src/main/resources/templates/board/skins/default/write.html
=> 게시판 추가 작업 준비중

src/main/java/org/teamproject/controllers/admin/ClaimController.java, src/main/java/org/teamproject/controllers/member/JoinForm.java, src/main/java/org/teamproject/controllers/orders/OrderController.java, src/main/java/org/teamproject/entities/OrderItem.java, src/main/java/org/teamproject/models/orders/CartInfoDeleteService.java, src/main/resources/messages/validations.properties, src/main/resources/templates/admin/claim/index.html, src/main/resources/templates/admin/outlines/_side.html, src/main/resources/templates/order/_items.html, src/main/resources/templates/order/end.html, src/main/resources/templates/order/view.html
회원가입 페이지 agree 필드 null 값 오류나서 수정했습니다.
근데 회원가입을 했을 때 데이터베이스에 mod_dt 값이 안들어가고, 비밀번호 암호화도 안됩니다.
또한, 로그인할때도 회원가입한 이메일과 비밀번호를 맞게 쳐도 로그인이 안됩니다. 이 부분은 따로 수정해야 할 것 같습니다.
=> 주문서 작업중 / 회원가입 페이지 오류 수정 / 주문관리,취소/교환/반품 페이지 병합
